# Generated by Django 6.0 on 2026-01-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_meeting',
        ),
    ]
