# Generated by Django 6.0 on 2026-01-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authority', '0006_initial'),
        ('Kudumbasree', '0002_delete_tbl_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_details', models.CharField(max_length=30)),
                ('meeting_date', models.DateField(auto_now_add=True)),
                ('meeting_time', models.TimeField()),
                ('meeting_todate', models.DateField()),
                ('meeting_location', models.CharField(max_length=30)),
                ('meeting_status', models.IntegerField(default=0)),
                ('kudumbasree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authority.tbl_kudumbasree')),
            ],
        ),
    ]
