# Generated by Django 6.0 on 2026-02-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0006_tbl_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=30)),
                ('notification_details', models.CharField(max_length=30)),
                ('notification_location', models.CharField(max_length=30)),
                ('notification_file', models.FileField(upload_to='Assets/File/User')),
            ],
        ),
    ]
