# Generated by Django 6.0 on 2026-02-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0007_tbl_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_notification',
            name='notification_status',
            field=models.IntegerField(default=0),
        ),
    ]
