# Generated by Django 6.0 on 2026-02-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0008_tbl_notification_notification_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_notification',
        ),
    ]
