# Generated by Django 6.0 on 2026-02-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
        ('Kudumbasree', '0009_delete_tbl_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=30)),
                ('notification_details', models.CharField(max_length=30)),
                ('notification_location', models.CharField(max_length=30)),
                ('notification_file', models.FileField(upload_to='Assets/File/User')),
                ('notification_status', models.IntegerField(default=0)),
                ('kudumbasree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kudumbasree')),
            ],
        ),
    ]
