# Generated by Django 6.0 on 2026-02-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_authority_tbl_authorityward'),
        ('Guest', '0005_initial'),
        ('Kudumbasree', '0010_tbl_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_details', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_file', models.FileField(upload_to='Assets/File/User')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('kudumbasree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kudumbasree')),
            ],
        ),
    ]
