# Generated by Django 6.0 on 2026-02-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0012_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(upload_to='Assets/File/User')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kudumbasree.tbl_product')),
            ],
        ),
    ]
