# Generated by Django 6.0 on 2026-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0014_tbl_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_attendance',
            name='attendance_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
