# Generated by Django 6.0 on 2026-02-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0015_alter_tbl_attendance_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.IntegerField(default=0)),
                ('fine_date', models.DateField(auto_now_add=True)),
                ('fine_status', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kudumbasree.tbl_members')),
            ],
        ),
    ]
