# Generated by Django 6.0 on 2026-02-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0016_tbl_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_fine',
            name='member',
        ),
        migrations.RemoveField(
            model_name='tbl_members',
            name='kudumbasree',
        ),
        migrations.RemoveField(
            model_name='tbl_members',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_attendance',
        ),
        migrations.DeleteModel(
            name='tbl_fine',
        ),
        migrations.DeleteModel(
            name='tbl_members',
        ),
    ]
