# Generated by Django 6.0 on 2026-02-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
        ('Kudumbasree', '0017_remove_tbl_fine_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_status', models.IntegerField(default=0)),
                ('kudumbasree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kudumbasree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.IntegerField(default=0)),
                ('fine_date', models.DateField(auto_now_add=True)),
                ('fine_status', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kudumbasree.tbl_members')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('attendance_status', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kudumbasree.tbl_meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kudumbasree.tbl_members')),
            ],
        ),
    ]
