# Generated by Django 6.0 on 2026-02-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0018_tbl_members_tbl_fine_tbl_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_date', models.DateField(auto_now_add=True)),
                ('saving_status', models.IntegerField(default=0)),
                ('saving_amount', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kudumbasree.tbl_members')),
            ],
        ),
    ]
