# Generated by Django 6.0 on 2026-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0019_tbl_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_meeting',
            name='meeting_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
