# Generated by Django 6.0 on 2026-03-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
        ('Kudumbasree', '0020_tbl_meeting_meeting_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chit_date', models.DateField(auto_now_add=True)),
                ('chit_status', models.IntegerField(default=0)),
                ('chit_amount', models.IntegerField(default=0)),
                ('chit_totalamount', models.IntegerField(default=0)),
                ('kudumbasree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kudumbasree')),
            ],
        ),
    ]
