# Generated by Django 6.0 on 2026-03-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0021_tbl_chit'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chitmembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chitmembers_status', models.IntegerField(default=0)),
                ('chit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kudumbasree.tbl_chit')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kudumbasree.tbl_members')),
            ],
        ),
    ]
