# Generated by Django 6.0 on 2026-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0022_tbl_chitmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chitmembers',
            name='chitmembers_date',
            field=models.DateField(null=True),
        ),
    ]
