# Generated by Django 6.0.3 on 2026-03-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_authority_tbl_authorityward'),
        ('Authority', '0009_initial'),
        ('CDS', '0007_initial'),
        ('Guest', '0005_initial'),
        ('Kudumbasree', '0023_tbl_chitmembers_chitmembers_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_notification',
            name='ads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CDS.tbl_ads'),
        ),
        migrations.AddField(
            model_name='tbl_notification',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authority'),
        ),
        migrations.AddField(
            model_name='tbl_notification',
            name='cds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authority.tbl_cds'),
        ),
        migrations.AlterField(
            model_name='tbl_notification',
            name='kudumbasree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kudumbasree'),
        ),
    ]
