# Generated by Django 6.0.3 on 2026-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudumbasree', '0024_tbl_notification_ads_tbl_notification_authority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_notification',
            name='notification_file',
            field=models.FileField(upload_to='Assets/File/Notification/'),
        ),
    ]
