# Generated by Django 6.0 on 2025-12-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category_remove_tbl_district_district_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
    ]
