# Generated by Django 6.0 on 2025-12-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=30)),
                ('Admin_email', models.CharField(max_length=30)),
                ('Admin_password', models.CharField(max_length=30)),
            ],
        ),
    ]
