# Generated by Django 6.0 on 2026-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_authoritytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authoritytype_name', models.CharField(max_length=30)),
            ],
        ),
    ]
