# Generated by Django 6.0 on 2026-01-17 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_authoritytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=30)),
                ('authority_email', models.CharField(max_length=30)),
                ('authority_contact', models.CharField(max_length=30)),
                ('authority_address', models.CharField(max_length=30)),
                ('authority_photo', models.FileField(upload_to='Assets/File/User')),
                ('authority_proof', models.FileField(upload_to='Assets/File/User')),
                ('authority_password', models.CharField(max_length=30)),
                ('authority_status', models.IntegerField(default=0)),
                ('authoritytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authoritytype')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_authorityward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authority')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
            ],
        ),
    ]
