# Generated by Django 6.0.3 on 2026-03-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_tbl_authority_tbl_authorityward'),
        ('CDS', '0004_delete_tbl_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_name', models.CharField(max_length=30)),
                ('ads_email', models.CharField(max_length=30)),
                ('ads_contact', models.CharField(max_length=30)),
                ('ads_password', models.CharField(max_length=30)),
                ('ads_photo', models.FileField(upload_to='Assets/ADS/')),
                ('authorityward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authorityward')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
