# Generated by Django 6.0.3 on 2026-03-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CDS', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ads',
        ),
    ]
