# Generated by Django 6.0 on 2026-01-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_authoritytype'),
        ('Guest', '0002_tbl_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='localplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace'),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward'),
        ),
    ]
