# Generated by Django 6.0 on 2026-01-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0008_remove_tbl_kudumbasree_authorityward_and_more'),
        ('Guest', '0003_tbl_user_localplace_tbl_user_ward'),
        ('User', '0003_remove_tbl_feedback_user_delete_tbl_complaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='localplace',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='ward',
        ),
        migrations.DeleteModel(
            name='tbl_authority',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
