# Generated by Django 6.0 on 2026-01-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_tbl_authority_tbl_authorityward'),
        ('Guest', '0004_remove_tbl_user_localplace_remove_tbl_user_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_kudumbasree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kudumbasree_name', models.CharField(max_length=30)),
                ('kudumbasree_email', models.CharField(max_length=30)),
                ('kudumbasree_contact', models.CharField(max_length=30)),
                ('kudumbasree_password', models.CharField(max_length=30)),
                ('kudumbasree_status', models.IntegerField(default=0)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authority')),
                ('authorityward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authorityward')),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='Assets/File/User')),
                ('user_password', models.CharField(max_length=30)),
                ('user_status', models.IntegerField(default=0)),
                ('authorityward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authorityward')),
                ('localplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
