# Generated by Django 6.0 on 2026-01-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_authoritytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_kudumbasree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kudumbasree_name', models.CharField(max_length=30)),
                ('Kudumbasree_email', models.CharField(max_length=30)),
                ('Kudumbasree_contact', models.CharField(max_length=30)),
                ('Kudumbasree_password', models.CharField(max_length=30)),
                ('Kudumbasree_status', models.IntegerField(default=0)),
                ('authoritytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authoritytype')),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
            ],
        ),
    ]
