# Generated by Django 6.0 on 2026-01-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_kudumbasree',
            old_name='Kudumbasree_contact',
            new_name='kudumbasree_contact',
        ),
        migrations.RenameField(
            model_name='tbl_kudumbasree',
            old_name='Kudumbasree_email',
            new_name='kudumbasree_email',
        ),
        migrations.RenameField(
            model_name='tbl_kudumbasree',
            old_name='Kudumbasree_name',
            new_name='kudumbasree_name',
        ),
        migrations.RenameField(
            model_name='tbl_kudumbasree',
            old_name='Kudumbasree_password',
            new_name='kudumbasree_password',
        ),
        migrations.RenameField(
            model_name='tbl_kudumbasree',
            old_name='Kudumbasree_status',
            new_name='kudumbasree_status',
        ),
    ]
