# Generated by Django 6.0 on 2026-01-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0002_rename_kudumbasree_contact_tbl_kudumbasree_kudumbasree_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_kudumbasree',
        ),
    ]
