# Generated by Django 6.0 on 2026-01-16 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_authoritytype'),
        ('Authority', '0003_delete_tbl_kudumbasree'),
        ('Guest', '0003_tbl_user_localplace_tbl_user_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_kudumbasree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kudumbasree_name', models.CharField(max_length=30)),
                ('kudumbasree_email', models.CharField(max_length=30)),
                ('kudumbasree_contact', models.CharField(max_length=30)),
                ('kudumbasree_password', models.CharField(max_length=30)),
                ('kudumbasree_status', models.IntegerField(default=0)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_authority')),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
            ],
        ),
    ]
