# Generated by Django 6.0 on 2026-01-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0004_initial'),
        ('Kudumbasree', '0002_delete_tbl_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_kudumbasree',
        ),
    ]
