# Generated by Django 6.0 on 2026-01-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_kudumbasree',
            name='ward',
        ),
    ]
