# Generated by Django 6.0 on 2026-01-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0007_remove_tbl_kudumbasree_ward'),
        ('Kudumbasree', '0004_delete_tbl_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_kudumbasree',
            name='authorityward',
        ),
        migrations.RemoveField(
            model_name='tbl_kudumbasree',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='tbl_kudumbasree',
            name='localplace',
        ),
        migrations.DeleteModel(
            name='tbl_authorityward',
        ),
        migrations.DeleteModel(
            name='tbl_kudumbasree',
        ),
    ]
