# Generated by Django 6.0.3 on 2026-03-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_tbl_authority_tbl_authorityward'),
        ('Authority', '0008_remove_tbl_kudumbasree_authorityward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cds_name', models.CharField(max_length=30)),
                ('cds_email', models.CharField(max_length=30)),
                ('cds_contact', models.CharField(max_length=30)),
                ('cds_password', models.CharField(max_length=30)),
                ('cds_photo', models.FileField(upload_to='Assets/CDS/')),
                ('authorityward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_authorityward')),
            ],
        ),
    ]
