# Generated by Django 6.0 on 2026-02-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='cart_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
